### ISSUE TITLE
field [lat_lon] is not a geo_point field

### ISSUE THREAD

**Issue by jasonfb** [karmi/retire#654] opened 2013-03-04 18:49 UTC
I researched  prior issues but am unable to figure this out.

```
        mapping do 
          indexes :merchandiser_manager, type: 'boolean'
          indexes :lat_lon, type: 'geo_point', lat_lon: true
        end
```

```
    def search_merchandiser_managers_by_proximity(lat, lng, radius) # specified in miles
      tire.search do
        query do
          all
        end        
        filter :term, merchandiser_manager: true
        filter :geo_distance, lat_lon: "#{lat}, #{lng}", distance: "#{radius}mi"  
        #debugger
      end    
```

```
 def to_indexed_json
    UserSearchIndexSerializer.new(self).to_json({})
 end
```

```
class UserSearchIndexSerializer < ActiveModel::Serializer
  attributes :id, :merchandiser_manager, :lat_lon

  root false

  def lat_lon    
    if object.profile_address.try(:lat)
      [object.profile_address.try(:lat),  object.profile_address.try(:lng)].join(',')
    else
      {}
    end
  end
end
```

When I debug inside of the tire.search  and when I examine self.url and self.to_json, I am able to reproduce this on the command line using curl, as follows:

curl -XGET http://localhost:9200/candi_development_users/user/_search -d "{\"query\":{\"match_all\":{}},\"filter\":{\"and\":[{\"term\":{\"merchandiser_manager\":true}},{\"geo_distance\":{\"lat_lon\":\"41.236, -73.4874\",\"distance\":\"10mi\"}}]},\"size\":10}"
{"error":"SearchPhaseExecutionException[Failed to execute phase [query], total failure; shardFailures {[6lvpurIQRo-8biuoGnSIaA][candi_development_users][0]: SearchParseException[[candi_development_users][0]: query[ConstantScore(NotDeleted(_:_))],from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"filter\":{\"and\":[{\"term\":{\"merchandiser_manager\":true}},{\"geo_distance\":{\"lat_lon\":\"41.236, -73.4874\",\"distance\":\"10mi\"}}]},\"size\":10}]]]; nested: QueryParsingException[[candi_development_users] field [lat_lon] is not a geo_point field]; }{[6lvpurIQRo-8biuoGnSIaA][candi_development_users][4]: SearchParseException[[candi_development_users][4]: query[ConstantScore(NotDeleted(_:_))],from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"filter\":{\"and\":[{\"term\":{\"merchandiser_manager\":true}},{\"geo_distance\":{\"lat_lon\":\"41.236, -73.4874\",\"distance\":\"10mi\"}}]},\"size\":10}]]]; nested: QueryParsingException[[candi_development_users] field [lat_lon] is not a geo_point field]; }]","status":500}

I tried both naming my filed "location" and also "lat_lon", also with and without the "lat_long: true" option on the mapping definition. (Part of what makes the docs a little confusing is that some places lat_lon is used as a field name, but elasticsearch docs also say it is an option on the geo_point type). 

Can someone see what I have done wrong here? I've tried everything I can think of, still getting field [lat_lon] is not a geo_point field  (or field [location] is not a geo_point field when I rename the field to location)

**Comment by brupm** [comment] 2013-03-04 22:30
Make sure before you index anything you create an empty index with the proper mappings. 

```
tire.index.delete
tire.create_elasticsearch_index
```

This will ensure the geo_point field is created in the index of the proper type. Otherwise it may be created as a "double" and then you will get that error. 

Once you run the `create_elasticsearch_index` check the mappings for the index at: GET `localhost:9200/index_name/_mapping

The field type should be listed as geo_point.

**Comment by jasonfb** [comment] 2013-03-04 23:03
we've been doing:

User.index.delete
User.import

Will try your method and get back to you

**Comment by jasonfb** [comment] 2013-03-04 23:10
Lo and behold... it is NOT in my mapping.

I think maybe my setting syntax is wrong. I 

```
      settings analysis: {
        filter: {
          edge_ngram_filter: {
            type: "edgeNGram", # an n-gram is a contiguous sequence of n items from a given sequence of text
            max_gram: 8,
            min_gram: 2,
            side: 'front' # only index n-grams beginning with the first letter
          }
        },
        analyzer: {
          edge_ngram_analyzer: {
            tokenizer: "lowercase", # divides text at non-letters and converts them to lower case
            filter: ["edge_ngram_filter"],
            type: "custom"
          }
        }
      } do
        mapping do 
          indexes :id, type: 'integer'
          indexes :merchandiser_user_id, type: 'string', analyzer: 'keyword'

          indexes :firstname, type: 'string', analyzer: "edge_ngram_analyzer"
          indexes :lastname, type: 'string', analyzer: "edge_ngram_analyzer"
          indexes :email, type: 'string', analyzer: "edge_ngram_analyzer"
          indexes :lat_lon, type: 'geo_point'
          indexes :merchandiser_manager, type: 'boolean'

          indexes :anonymous, type: 'boolean', included_in_all: false
        end
      end

```

Does the "settings analysis" block at the top specify that all the fields in the mapings are ngram filters? I'm confused, do I need to specify two settings blocks, one for my ngram filter-able fields and another for my other kinds of fields?

When I do this http://localhost:9200/candi_development_users/_mapping

I see this result, which clearly does not show either lat_lon (geo_point) or merchandiser_manager (boolean)

{"candi_development_users":{"user":{"properties":{"anonymous":{"type":"boolean"},"email":{"type":"string","analyzer":"edge_ngram_analyzer"},"firstname":{"type":"string","analyzer":"edge_ngram_analyzer"},"id":{"type":"integer"},"lastname":{"type":"string","analyzer":"edge_ngram_analyzer"},"merchandiser_user_id":{"type":"string","analyzer":"keyword"}}}}}

**Comment by brupm** [comment] 2013-03-04 23:44
All you should need is:

``` ruby
mapping do
  indexes :user_lat_lon, type: "geo_point"
end
```

**Comment by brupm** [comment] 2013-03-04 23:45
Maybe start with the basics in the mappings/settings block and then add your customizations one by one, something along the way is causing issues.

**Comment by karmi** [comment] 2013-03-05 08:34
@jasonfb Your syntax is correct. `lat_lon` indeed isn't a very good name for the field, I'd use `location` or similar.

`User.index.delete && User.import` is correct, _but_ the index is not created by the import method, instead Elasticsearch creates the index with dynamic mapping. This is the root cause of your error. The correct way would be:

```
User.index.delete
User.create_elasticsearch_index
User.import
```

Or use the Rake task, `rake tire:import CLASS="User" FORCE=true`. Let me know if this helps.

**Comment by karmi** [comment] 2013-03-07 16:08
Closing, feel free to reopen with more info if needed...

**Closed as completed by karmi** 2013-03-07 16:08 UTC

**Comment by jasonfb** [comment] 2013-03-07 16:26
Yes thank you, I got this working. I think if you leave out the step create_elasticsearch_index it doesn't re-create the index with the new fields, and so I was not seeing them in there and getting that message.
