### ISSUE TITLE
Index settings in Persistence mode

### ISSUE THREAD

**Issue by kshnurov** [karmi/retire#414] opened 2012-07-25 14:52 UTC
I can't make index settings, boost and analyzers work in persistence mode. What am I doing wrong?

```
class Item
  include Tire::Model::Search
  include Tire::Model::Callbacks
  include Tire::Model::Persistence

  settings :analysis => {
             :analyzer => {
               :standard => {
                 "tokenizer"  => "standard",
                 "filter"     => ["stop", "trim"],
                 "type"         => "standard" 
               },
               :word_analyzer => {
                  "tokenizer"    => "lowercase",
                  "filter"       => ["stop", "word_ngram"],
                  "type"         => "custom"
                }
             },
             :filter => {
               :word_ngram  => {
                 "type"     => "nGram",
                 "max_gram" => 5,
                 "min_gram" => 3 
               }
             }
          } do
    mapping do
      index_name 'items'
      indexes :gs_id, :type => :long
      indexes :available, :type => :boolean, :default => false
      indexes :name,        :boost => 2, :analyzer => 'word_analyzer'
      indexes :price, :type => :float
      indexes :description,        :analyzer => 'word_analyzer'
    end
  end
  property :gs_id, type: 'long'
  property :available, type: 'boolean', default: false
  property :name, :boost => 2, :analyzer => 'word_analyzer'
  property :price, type: 'float'
  property :description,        analyzer: 'word_analyzer'
end
```

As a result:

```
1.9.3-p125 :006 > Item.index.delete
 => true 
1.9.3-p125 :007 > Item.index.mapping
 => nil 
1.9.3-p125 :008 > Item.create(:name => '123')
 => #<Item:0x007fdc8408d708 @available=false, @name="123", @validation_context=nil, @errors=#<ActiveModel::Errors:0x007fdc8408cd08 @base=#<Item:0x007fdc8408d708 ...>, @messages={}>, @__tire__=#<Tire::
Model::Search::InstanceMethodsProxy:0x007fdc8408bd18 @instance=#<Item:0x007fdc8408d708 ...>>, @id="M2LxBP1KRSyloK4LXP3ZOg", @attributes={"_index"=>"items", "_type"=>"item", "_version"=>1, "matches"=>n
il}> 
1.9.3-p125 :009 > Item.index.mapping
 => {"item"=>{"properties"=>{"available"=>{"type"=>"boolean"}, "name"=>{"type"=>"string"}}}} 
1.9.3-p125 :010 > Item.index.settings
 => {"index.number_of_shards"=>"5", "index.number_of_replicas"=>"1", "index.version.created"=>"190899"}
```

**Comment by karmi** [comment] 2012-07-25 14:56
Well, `class Item` is kinda dubious name in _Tire_, since that can clash with [`Tire::Results::Item`](https://github.com/karmi/tire/blob/master/lib/tire/results/item.rb). Not sure if that's your problem or not...

**Comment by kshnurov** [comment] 2012-07-25 15:07
Renamed it to Product - no changes.

**Comment by kshnurov** [comment] 2012-07-25 15:34
Well, found a very strange way:

```
Item.index.delete
```

After that I close and open rails console again and everything is great:

```
1.9.3-p125 :001 > Item.index.mapping
 => {"item"=>{"properties"=>{"available"=>{"type"=>"boolean"}, "category"=>{"type"=>"string"}, "currencyId"=>{"type"=>"string"}, "description"=>{"type"=>"string", "analyzer"=>"word_analyzer"}, "gs_cat
egory_id"=>{"type"=>"long"}, "gs_id"=>{"type"=>"long"}, "gs_product_key"=>{"type"=>"string"}, "merchant_id"=>{"type"=>"long"}, "model"=>{"type"=>"string"}, "name"=>{"type"=>"string", "boost"=>2.0, "an
alyzer"=>"word_analyzer"}, "original_picture"=>{"type"=>"string"}, "param"=>{"type"=>"string"}, "params"=>{"type"=>"string"}, "picture"=>{"type"=>"string"}, "price"=>{"type"=>"float"}, "thumbnail"=>{"
type"=>"string"}, "url"=>{"type"=>"string"}, "vendor"=>{"type"=>"string"}, "vendorCode"=>{"type"=>"string"}}}} 
```

Why Item.index.create creates empty mapping? How to create right mapping from console? What magic happens, when I reopen console? :)

**Comment by karmi** [comment] 2012-07-25 15:54
> What magic happens, when I reopen console? :)

Lots of possible culprits, Rails' autoloading, etc...

The correct way to create a model index is either:

```
# NOTE: Will _not_ create an index if it exists.
MyModel.create_elasticsearch_index
```

or, more manually:

```
MyModel.index.create mappings: MyModel.mapping_to_hash, settings: MyModel.settings
```

**Comment by driki** [comment] 2012-08-04 18:25
Hi,

I'm also running into an issue getting the index setting working in Persistance mode and have tried Document.create_elasticsearch_index. I have an index named 'municipalities' and two classes 'Municipality' and 'Document'. The Municipality documents exist in the 'municipalities' index as a 'municipality' type. Document types are also in the same 'municipalities' index stored as a 'document' type. Any thoughts about how to configure the settings or write code for my Document and Municipality classes so that I can use the explicit mappings defined in both regardless of which type was created first?

In my case the 'municipalities' index already exists prior to a new Document being created and added to the index. When I call: 

```
1.9.3p125 :004 > Document.create_elasticsearch_index
 => nil 
```

The result is nil which I'm guessing is because the 'municipalities' index already exists? When I destroy the 'municipalities' index and then save a Document

```
doc = Document.new(:classification => "minutes", :municipality_state => 'MA', :municipality_slug => 'ma-somerville', :content_url => 'http://www.google.com')
doc.save
```

I can see that the explicit Document mapping settings are used, but if I create a Municipality and persist it first I do not get the explicit Document mapping. Below is the result of saving a Document prior to a Municipality.

```
{
  "municipalities": {
    "document": {
      "properties": {
        "classification": {
          "index": "not_analyzed",
          "type": "string"
        },
        "content_type": {
          "index": "not_analyzed",
          "type": "string"
        },
        "content_url": {
          "index": "not_analyzed",
          "type": "string"
        },
        "id": {
          "index": "not_analyzed",
          "type": "string"
        },
        "municipality_name": {
          "index": "not_analyzed",
          "type": "string"
        },
        "municipality_slug": {
          "index": "not_analyzed",
          "type": "string"
        },
        "municipality_state": {
          "index": "not_analyzed",
          "type": "string"
        }
      }
    }
  }
}
```

This is the mapping for the Municipality class if an instance is persisted after a Document. Notice none of the explicit mapping settings are being used.

```
{
  properties: {
    full_name: {
      type: "string"
    },
    id: {
      type: "string"
    },
    name: {
      type: "string"
    },
    slug: {
      type: "string"
    },
    state: {
      type: "string"
    }
  }
}  
```

The Municipality class

```
require 'active_model'
class Municipality

  include Tire::Model::Persistence

  index_name 'municipalities'

  mapping do
    indexes :id, :index => 'not_analyzed'
    indexes :state, :index => 'not_analyzed'
    indexes :slug, :index => 'not_analyzed'
    indexes :population, :index => 'not_analyzed', :type => 'integer'
    indexes :population_density, :index => 'not_analyzed', :type => 'float'
    indexes :latitude, :index => 'not_analyzed', :type => 'float'
    indexes :longitude, :index => 'not_analyzed', :type => 'float'
  end


  property :id
  property :name
  property :state
  property :slug
  property :full_name
  property :website
  property :website_accept_cookies
  property :website_linkable_domains
  property :website_skip_links
  property :website_strip_params
  property :code_fips
  property :code_gnis
  property :population
  property :population_density
  property :race_american_indian
  property :race_asian
  property :race_black
  property :race_hispanic
  property :race_multiple
  property :race_non_hispanic
  property :race_non_hispanic_white
  property :race_other
  property :race_pacific_islander
  property :race_white
  property :diversity
  property :area_land
  property :area_water
  property :latitude
  property :longitude
  property :housing_units
  property :housing_vacancies
  property :created_at
  property :updated_at
end
```

And the Document class

```
require 'active_model'
class Document

  include Tire::Model::Persistence

  index_name 'municipalities'

  mapping do
    indexes :content_url, :index => 'not_analyzed'
    indexes :id, :index => 'not_analyzed'
    indexes :classification, :index => 'not_analyzed'
    indexes :content_type, :index => 'not_analyzed'
    indexes :municipality_name, :index => 'not_analyzed'
    indexes :municipality_slug, :index => 'not_analyzed'
    indexes :municipality_state, :index => 'not_analyzed'    
  end

  property :id
  property :classification
  property :content_type
  property :content_url  
  property :created_at
  property :extracted_text
  property :last_modified_at
  property :legislative_body
  property :likely_date
  property :municipality_name
  property :municipality_slug
  property :municipality_state
  property :phone_numbers
  property :title
  property :updated_at
end
```

Thanks,
Matt

**Comment by karmi** [comment] 2012-10-19 10:01
Hello, really can't reproduce the issue, see working code below:

``` ruby
require 'tire'

Tire.index('municipalities-test').delete

class Document

  include Tire::Model::Persistence

  index_name 'municipalities-test'

  mapping do
    indexes :id,            index: 'not_analyzed'
    indexes :content_url,   index: 'not_analyzed'
    indexes :content,       analyzer: 'snowball'
  end

  property :id
  property :content_url  
  property :created_at
  property :content
end

mapping = Tire.index('municipalities-test').mapping

# p mapping

puts "ID is not_analyzed:    %s" % [ mapping['document']['properties']['id']['index'] == 'not_analyzed' ]
puts "Content is snowballed: %s" % [ mapping['document']['properties']['content']['analyzer'] == 'snowball' ]
```

Closing for now, feel free to reopen or submit new issue if you feel there's a problem.

Also, the long code listings make the issue hard to digest -- better use gists/pasties/etc in a case like that.

**Closed as completed by karmi** 2012-10-19 10:01 UTC
