### ISSUE TITLE
Tire's support for Fixnum-type id

### ISSUE THREAD

**Issue by john-bai** [karmi/retire#419] opened 2012-07-29 20:59 UTC
Hi Karmi,

I'm using ActiveRecord with auto-incrementing numbers as the id. I noticed collection.rb uses the _id field of the ES hits response over the _source id field during deserialization. This doesn't work well in my case since the object-representation of each search result will have a String-type id attribute (the ES _id field will always be a string type). Comparison operators fail once I start comparing Tire search results with real ActiveRecord objects (comparison of Fixnum with String failed).

Would you have a suggestion for my scenario or perhaps could explain the choice to use _id over _source id? Here's a snippet of the relevant code:

``` ruby
# collection.rb:27-32
hits.map do |h|
  document = {}

  # Update the document with content and ID
  document = h['_source'] ? document.update( h['_source'] || {} ) : document.update( __parse_fields__(h['fields'])
  document.update( {'id' => h['_id']} )
```

and a snippet of the JSON response from ES that shows the long-type id attribute of _source:

``` javascript
{
   "took":2,
   "timed_out":false,
   "_shards":{
      "total":5,
      "successful":5,
      "failed":0
   },
   "hits":{
      "total":1,
      "max_score":1.0,
      "hits":[
         {
            "_index":"products",
            "_type":"product",
            "_id":"129",
            "_score":1.0,
            "_source":{
               "created_at":"2012-07-28T22:51:33Z",
               "id":129,
```

**Comment by karmi** [comment] 2012-08-01 12:27
Hi, ES returns the ID as a String since usually IDs in ES are in a format like `abc-123-defQWZ` etc. The choice of `_id` over `source.id` is just that it seems like a safer bet.

Normally, this should not make mess up with `ActiveRecord.fine` etc -- could you post a snippet of code how are you comparing the objects?

**Comment by john-bai** [comment] 2012-08-04 06:18
I see what you mean about ActiveRecord.find being flexible about using a String id param for lookup. In all honesty I can also add such flexibility into my comparison logic and things will work just fine. Here's an example of a comparison that wouldn't go well:

``` ruby
products = Product.search("xbox games");

@unowned_products = []

products.each do |product|
  @unowned_products << product unless current_user.owned_product_ids.include?(product.id)
end
```

I can use to_i to get it working, so no blockers there. I was just curious to ask about the preference of _id (which you explained).

What do you think about using _source.id if defined, otherwise use _id?

``` ruby
document = h['_source'] ? document.update( h['_source'] || {} ) : document.update( __parse_fields__(h['fields']) )
document.update( {'id' => h['_id']} ) if document['id'].nil?
```

**Comment by karmi** [comment] 2012-10-19 09:53
@jtherrell Hello, terribly sorry for the silence... I understand the issue, but the problem is that _Tire_ should really use the document ID as authoritative, not the `_source.id` value. Moreover, when using the `:load` option, you can disable loading `_source` altogether, since you're getting data from the database -- again, much cleaner to just get document ID then having to add `fields: ['id']`.

Closing this for now, since it's so old... Feel free to re-open if you feel it's needed!

**Closed as completed by karmi** 2012-10-19 09:53 UTC
