### ISSUE TITLE
Merge stored attributes with loaded model attributes

### ISSUE THREAD

**Issue by martinciu** [karmi/retire#364] opened 2012-06-03 16:43 UTC
Hi,

I'd like to be able to merge stored attributes ( from `_source` or `fields`) into loaded model (via `:load => true` flag). Is there easy way to do it? I was thinking of wrapping loaded model into some `ResultDecorator`. 

What do you think about it?

Thanks!

**Comment by karmi** [comment] 2012-10-23 13:29
Duplicate of #368

**Closed as completed by karmi** 2012-10-23 13:29 UTC
