### ISSUE TITLE
Multithreading and the curb driver

### ISSUE THREAD

**Issue by rb2k** [karmi/retire#144] opened 2011-11-07 11:24 UTC
I use tire with the curb driver in a sinatra application.
I get an "Invalid easy handle" when trying to access "Curl::Err::MultiBadEasyHandle" in one request while another request is already searching. This is probably due to curb not being able to share the handles

my configure block in sinatra has these tire specific elements:

```
#set up curb as http client for Tire
  extend Tire::DSL
  configure do
    client Tire::HTTP::Client::Curb
  end

  set :tire, Tire
  require 'tire/http/clients/curb'
```

Not sure if that is my architecture or something tire internal

**Comment by vhyza** [comment] 2011-11-07 13:55
Hello,

it is weird. Do you have the same problem with `HTTP::Client::RestClient`?

**Comment by karmi** [comment] 2011-11-07 21:09
It does not ring any bell to me. The Curb instance is instantiated once and then reused: https://github.com/karmi/tire/blob/master/lib/tire/http/clients/curb.rb#L10.

**Comment by rb2k** [comment] 2011-11-07 21:13
That might be the problem. Sinatra spawns a new thread for each request on most servers afaik.
Since the curb instance is instantiated once and curb isn't threadsafe, that might make Tire not threadsafe. Not sure how to solve that.

**Comment by karmi** [comment] 2011-11-08 06:29
@rb2k: Yeah, I had this suspicion. You can just create another Curb-based client, which creates new client for every request, copying the [~50 lines of code in Tire](https://github.com/karmi/tire/blob/master/lib/tire/http/clients/curb.rb#L10) into your own file, and pass it to `Tire.configure { client MyCurbClient }`.

Is this all about working around the timeout issue?

**Comment by karmi** [comment] 2011-11-10 13:06
@rbk: Ping, any luck with it?

**Comment by rb2k** [comment] 2011-11-10 15:28
Sorry haven't found the time to open that project since then :(
It is on my "to do" list though :)

**Comment by karmi** [comment] 2011-11-17 17:14
Ping, any news? :)

**Comment by karmi** [comment] 2012-03-20 22:03
@rb2k Marc, let's close this ancient thing for now and open a new one if the problem still persist?

**Comment by rb2k** [comment] 2012-03-20 22:07
Yeah, probably the best solution.
Sorry that I didn't find the time to actually try that again :-/

**Comment by karmi** [comment] 2012-03-20 22:14
@rb2k No, sorry it took _me_ so long to get back to this :)

**Comment by brupm** [comment] 2013-03-27 01:29
Just ran into this big time in production. As I see it using curb is not possible as it is.

**Comment by brupm** [comment] 2013-03-27 04:47
HI @karmi with unicorn being the defacto production server, I believe multithreading capability on the the curb client in tire is a must, let me know how I can help.

**Comment by karmi** [comment] 2013-03-27 06:42
@brupm A piece of Ruby code which I can run and which reliably demonstrates the issue would be the perfect help at the moment.

**Closed as completed** 2013-03-27 09:03 UTC

**Comment by brupm** [comment] 2013-04-24 00:36
Seeing lots of "Curl::Err::MultiBadEasyHandle: CURLError: Invalid easy handle". Upon further investigation looks like the client it is still sharing handles. I am not too sure yet how, haven't been able to reproduce the issue outside of the application. 

@karmi the sample code provided in this commit https://github.com/karmi/tire/commit/ec56611c75fbec7da1c31b5ff3ccffd0923140af must not be triggering the issues. 

The backtrack points to:

```
vendor/bundle/ruby/1.9.1/gems/curb-0.8.3/lib/curl/easy.rb:55:in `add
vendor/bundle/ruby/1.9.1/gems/curb-0.8.3/lib/curl/easy.rb:55:in `perform
vendor/bundle/ruby/1.9.1/gems/tire-0.5.7/lib/tire/http/clients/curb.rb:27:in `http_post
vendor/bundle/ruby/1.9.1/gems/tire-0.5.7/lib/tire/http/clients/curb.rb:27:in `get
vendor/bundle/ruby/1.9.1/gems/tire-0.5.7/lib/tire/search.rb:136:in `perform
vendor/bundle/ruby/1.9.1/gems/tire-0.5.7/lib/tire/search.rb:35:in `results
vendor/bundle/ruby/1.9.1/gems/tire-0.5.7/lib/tire/model/search.rb:105:in `search
```

Which isn't much help at all. I will try go dig in a bit more to find out why the muti-threading is not working. 

On another note have you see https://github.com/drbrain/net-http-persistent? Appears to be the ideal alternative.

**Comment by karmi** [comment] 2013-04-24 14:18
@brupm The HTTP is pluggable, so it should be easy to add whatever client just by adding a `Tire::HTTP::Client::XYZ` class. There's also a [Faraday](https://github.com/karmi/tire/blob/master/lib/tire/http/clients/faraday.rb)-based client, which should allow you to use whatever adapter is [supported](https://github.com/lostisland/faraday/tree/master/lib/faraday/adapter).

The `Thread.current[]` fix should really prevent the issue -- make sure you use proper version etc?

**Comment by brupm** [comment] 2013-04-24 19:55
@karmi Thread.current[] does not seem to solve the issue 100%. It did reduce the # of errors but they still happen quiet frequently.

I put together this https://github.com/karmi/tire/pull/713 would love some feedback.

**Comment by brupm** [comment] 2013-04-24 22:50
Something interested I noticed... The `Curl::Err::MultiBadEasyHandle: CURLError: Invalid easy handle` seem to happen when the prod application is restarted, perhaps there is some kind of teardown/cleanup that needs to happen? I am not too familiar with multithreading. 
/cc @karmi @nz
