### ISSUE TITLE
Highlighting with Boosting & Scoring

### ISSUE THREAD

**Issue by mikeg250** [karmi/retire#120] opened 2011-10-06 14:50 UTC
Will Tire allow Highlighting to work with custom_score or boosting?  
I ask because I saw this recent open pull request on Elasticsearch https://github.com/elasticsearch/elasticsearch/pull/1315.

Thanks,
- mike

**Comment by karmi** [comment] 2011-10-06 14:54
If it will be available in ES and if it will make sense to expose it via Tire, yes.

Closing as a duplicate of karmi/tire#118.

**Closed as completed by karmi** 2011-10-06 14:54 UTC

**Comment by mikeg250** [comment] 2011-10-06 15:04
Sorry, not sure I understand.  Does your response mean that ES and Tire do not currently support Highlighting with boosting?  

Thanks again (your Tire gem is pretty cool!)
- mike

**Comment by karmi** [comment] 2011-10-06 15:12
Sorry, I don't understand your question. The link you're posting is to a pull request, requesting a feature be added into ES. As such, Tire does not support such feature, because it's not in the ES. I have no personal knowledge and experience with highlighting as related to custom score and boosting.

**Comment by mikeg250** [comment] 2011-10-06 15:46
Thank you. I’m new to all this, so I didn’t realize exactly what a pull request was.   Your response makes sense to me now.
