### ISSUE TITLE
Creating and Indexing new records from a separate server.

### ISSUE THREAD

**Issue by invzn** [karmi/retire#253] opened 2012-02-23 18:50 UTC
I have:

1) Rails 3.0 App + ElasticSearch Server running on Server1.

2) Database running on Server2.

3) Workers running on Server3.

4) Rails 3.0 App uses the Database on Server2.

5) Workers insert records into the Database on Server2.

Problem:

My Rails 3.0 App doesn't find any new records inserted by the Workers through ElasticSearch.

Question:

How do I get the Workers to index records in ElasticSearch as it inserts it into the Database?

Thanks,
Chris

**Comment by karmi** [comment] 2012-02-23 19:36
Hi, by default, _Tire_ hooks into the `ActiveRecord#after_save`, so it does not matter where everything runs... It's hard to know what's going on without some gist or error trace...

**Comment by invzn** [comment] 2012-03-14 00:11
I figured it out lol. Such a noob.

Tire.configure do
  url 'http://www.example.com:1234'
end

fixed it =)

**Comment by karmi** [comment] 2012-03-14 08:00
@callenrosario Great, if the issue is fixed, could you please close the issue?

**Closed as completed** 2012-03-14 15:59 UTC
