### ISSUE TITLE
Liberation of mapping definition from the one mapping block

### ISSUE THREAD

**Issue by chrisberkhout** [karmi/retire#153] opened 2011-11-24 04:07 UTC
I'd like to have more flexibility in how I define mappings, rather than the current way of a single mapping block. It occurred to me that this might already be possible, but looking through the code it seems that you can't add to a mapping once it's been created.

My use case is that I've got a bunch of models, and I want several of them to be part of a workflow system. This involves some fields and some methods that I've extracted into a module. I'd like to have their mappings in the module too.

**Comment by karmi** [comment] 2011-11-29 21:04
Hi Chris, do you have any example code as a "suggestion" so I understand better? 

The mapping itself can be changed freely, just by calling the `mapping` method multiple times, but the problem is of course the `create_elasticsearch_index` call. I haven't found a better way how to do this.

Of course it would be trivial to support something like `mapping :create => false do ... end` so you can define the mapping and the call the `create_elasticsearch_index` method yourself.

**Comment by niuage** [comment] 2012-01-18 00:54
I really need this too.

With solr, you can call `searchable` several times, to build what fields should be indexed. This way, it's easy to extract this stuff into modules.
For instance, I have a Geolocated module, and I would just have something like:

```
included do
    tire.mapping do
        indexes :location, type: 'string', analyzer: 'snowball
        indexes :lat_lon, type: 'geo_point'
    end
 end
```

And I would not need to repeat these lines in every geolocated model. It would be awesome if you could provide a way to do this.

**Comment by chrisberkhout** [comment] 2012-02-27 03:27
Sorry for long delay! My suggestion is that indexes just works outside a block.

So, this code:

```
class Venue
  include Tire::Model::Search
  include Tire::Model::Callbacks
  index_name "some_index_name"
  #...
  mapping do
    indexes :location, type: 'string', analyzer: 'snowball
    indexes :lat_lon, type: 'geo_point'
  end
end
```

...can become:

```
module Geolocated
  included do
    indexes :location, type: 'string', analyzer: 'snowball
    indexes :lat_lon, type: 'geo_point'
  end
end

class Venue
  include Tire::Model::Search
  include Tire::Model::Callbacks
  index_name "some_index_name"
  #...
  include Geolocated
end
```

It could also stay wrapped in a block, as in @niuage's example. The important thing is just that you can extract parts of a class's mapping definition into a module.

I see the trouble in delaying the index check/creation until the end. @floere put me on to this technique:

```
END { code to be executed here }
```

http://ruby.runpaint.org/flow#begin-exit-handler

Which I believe could be used to make things happen after the whole of a class definition has been loaded up.

**Comment by karmi** [comment] 2012-03-11 10:41
Hello Chris, sorry for all these delays... I like the extraction of the `indexes` logic to module _very much_!

As always, @floere is absolutely right :) I agree it would be a perfect handler for executing the `create_elasticsearch_index` method. Feel free to take a hit on the issue! Otherwise I'll try to have a look in it soonish.

**Comment by floere** [comment] 2012-03-11 10:57
@karmi Thanks for the flowers. Happy to help :)

**Comment by karmi** [comment] 2012-03-27 12:57
Hey @chrisberkhout, sorry, another delay. Hmm... been playing with the `END` handler, and I see the problem that when you `require` the file, it really does not fire the handler. Have you had any success with it?

**Comment by demersus** [comment] 2012-03-27 17:37
Wow, this would be a great addition! I find myself duplicating the same mapping fields across multiple subclassed models.

**Comment by floere** [comment] 2012-03-27 20:05
@karmi @chrisberkhout Sorry for the confusion about the `END` block – each `END`'s block is only run at the very end, when the interpreter exits, which is not useful to you, I understand. Please see https://gist.github.com/2219741. A `BEGIN` however, is run each time when `load`ing (i.e. executing the statements in) the file, or once when requiring (since that results in only loading once).

**Comment by karmi** [comment] 2012-10-19 12:30
OK, hello from the future guys! :)

Two things:
1. I think _everybody_ should just create their indices in advance, and use the provided auto-creation only as a nice sweetie.
2. It's pretty doable to extract mapping into modules, as Chris suggested (copying from another issue I solved):

``` ruby
require 'tire'
require 'active_record'

Tire.index('articles') { delete }

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ":memory:" )

ActiveRecord::Migration.verbose = false
ActiveRecord::Schema.define(version: 1) do
  create_table(:articles) { |t| t.string :title }
  create_table(:people)   { |t| t.string :title }
end

module Searchable

  def self.included(base)

    p "Included in #{base}"

    base.class_eval do
      include Tire::Model::Search

      tire do
        mapping do
          indexes :title,   type: 'string', analyzer: 'snowball'
        end
      end
    end
  end
end

class Article < ActiveRecord::Base
  include Searchable
end

class Person < ActiveRecord::Base
  include Searchable
end

Article.tire.create_elasticsearch_index

puts "Article mapping:",
     Article.tire.mapping,
     '---'

puts "Create an article:",
     (article = Article.create title: 'Testing...'),
     '---'

puts "Update index...",
     article.tire.update_index,
     article.tire.index.refresh,
     '---'

puts "Perform search:",
     Article.tire.search('title:test').map { |a| "ID: #{a.id}, title: #{a.title}" },
     '---'

# The same thing with people...

Person.tire.create_elasticsearch_index

puts "Person mapping:",
     Person.tire.mapping

# ...
```

So, closing for now...

**Closed as completed by karmi** 2012-10-19 12:30 UTC
