### ISSUE TITLE
Give a name to facet ranges

### ISSUE THREAD

**Issue by niuage** [karmi/retire#208] opened 2012-01-18 16:26 UTC
Hey,

In Sunspot, you can do the following:

```
bod = Time.zone.now.beginning_of_day
facet :start_time do
    row :past do
        with(:from).less_than bod - 1.day
    end
    row :today do
        with :from, bod..(bod + 1.day)
    end
    row :week do
        with :from, (bod)..(bod + 7.days)
    end
    #...
end
```

When I switched to elastic search, I replaced the above by:

```
facet("timeline") do
    range :from, [
      { from: bod, to: bod+1.day }, #day
      { from: bod, to: bod+7.days }, #week
      { from: bod, to: bod+30.days }, #month
      { from: bod }, #upcoming
      { to: bod } #past
    ]
end
```

I was wondering if it was possible to give ranges some kind of identifiers, to make it easier when displaying the facets.
Also, if you know a better way to do it, dont hesitate.

Thanks

**Comment by agnellvj** [comment] 2012-02-02 21:03
The problem is that ElasticSearch doesn't support naming each range. I worked around this issue by defining my set of ranges statically in my code. Then after I get the facet data back from ElasticSearch, I use the static ranges to match each item back with the range data from ElasticSearch. It's hacky, but the only way to be named after coming back from ElasticSearch.

**Comment by niuage** [comment] 2012-02-02 21:08
I also found a way to handle that, I was just wondering if tire had some kind of built in way to do it. Thanks for your answer :)

**Comment by karmi** [comment] 2012-03-20 22:16
Hey, sounds like an interesting question for @kimchy :), but let's close this for now and let's open a new issue if the problem is stil stinging!

**Closed as completed by karmi** 2012-03-20 22:16 UTC
