### ISSUE TITLE
ActiveRecord fields not in database

### ISSUE THREAD

**Issue by kbaum** [karmi/retire#33] opened 2011-06-10 15:01 UTC
I am trying to define a custom mapping block on my ActiveRecord object for fields that are not in my database.  I noticed that tire is explicitly  deleting these fields when i call to_indexed_json.

```
else
     self.serializable_hash.
       reject { |key, value| ! self.class.mapping.keys.map(&:to_s).include?(key.to_s) }.
       to_json
end
```

What is the proper way of defining fields that are not attributes within ActiveRecord?

Thanks!

**Comment by pacoguzman** [comment] 2011-06-10 15:10
Define to_indexed_json instance method with all the field you need in your model then tire call it

**Comment by karmi** [comment] 2011-06-10 15:11
Hi, what the snipped really does is throwing out any attributes which are not included in the `mapping` block, _if_ the mapping was defined.

You have to redefine `to_indexed_json` in your case, there's info about that in the Readme. You should be able to simply something like:

```
class Article
  def to_indexed_json
    to_json(:methods => ['character_count'])
  end
end
```

I'm not happy with the current implementation of redefininig `to_indexed_json`, it's too low level, although it works...

**Comment by kbaum** [comment] 2011-06-10 15:11
Hmmm.. i did that and i see this error:

```
ActiveRecord::UnknownAttributeError Exception: unknown attribute: subject
```

**Comment by karmi** [comment] 2011-06-10 15:13
Could you post a more complete example?

**Comment by kbaum** [comment] 2011-06-10 15:16
Of course.  Here is my AR object:

https://gist.github.com/81acc2128cf3427acec5

I am using activerecord-3.0.7, tire-0.1.8, and ruby-1.9.2-p180.

**Comment by karmi** [comment] 2011-06-10 15:23
Well, this is how to do it https://gist.github.com/0cb9b0df72b7bbe13767, AFAIK.

You have to include the `permalink` method in mapping, and then just call `self.to_json(:methods => :permalink)`.

**Comment by kbaum** [comment] 2011-06-10 15:23
Just updated the gist to have the error too.

**Comment by kbaum** [comment] 2011-06-10 15:32
self.to_json with methods does not seem to work because to_json returns a nested hash with the object name as the key.  For example:

```
self.to_json(:methods=>[:subject])
```

yields

"{\"email_message\":{\"created_at\":\"2011-06-10T15:28:28Z\",\"date\":\"2010-08-03T07:13:49Z\",\"downloaded\":null,\"email_account_id\":1,\"email_file_path\":\"/gmail.com/weshopemailsync/%5BGmail%5D%2FAll+Mail/22.eml\",\"from_address\":\"somone@gmail.com\",\"id\":1,\"order\":false,\"order_total\":null,\"pop_id\":22,\"shipping\":false,\"store_id\":null,\"to_address\":\"webrat@googlegroups.com\",\"uid\":22,\"updated_at\":\"2011-06-10T15:28:28Z\",\"user_id\":2,\"subject\":\"[webrat] webrat, mechanize and http proxies\"}}"

**Comment by kbaum** [comment] 2011-06-10 15:41
Ok, i think i see the issue.  Tire is calling new with the subject attribute but the subject attribute is read-only.  Is there a way to tell tire to only construct attributes with what is in the relational database?

```
object = Configuration.wrapper.new(document)
```

Thanks!

**Comment by karmi** [comment] 2011-06-10 17:29
> to_json with methods does not seem to work because to_json returns a nested hash with the object name as the key.

You have to set `:root => false`, or `include_root_in_json = false`.

For the read-only thing, that's currently a big sore spot. See issues karmi/tire#11 and karmi/tire#12. There's a "solution" listed in issue karmi/tire#10. All this should be easier once the "proxy object" feature is implemented.

**Comment by kbaum** [comment] 2011-06-10 18:17
That makes sense.  

Question, regarding instanciating the active record class, does that mean that elastic search stores all of the attributes as well because i am passing some pretty large attributes?  Was under the impression that it would search for the attribute and then look up the underlying hits in the database.

Is there a way to tell it not to store the full content if the answer to above is yes?

Thanks!

**Comment by karmi** [comment] 2011-06-10 21:06
Yes, ES does store all the JSON you throw at it -- that's great because then you don't _have_ to query the database, in most cases. This is seriously on the biggest benefits of ES.

You can disable storing the fields, or disable storing the JSON altogether, please refer to ES documentation, eg. http://www.elasticsearch.org/guide/reference/mapping/source-field.html.

As for _Tire_, it is just a wrapper around ES API, so yes, with proper mapping, it would only index specific fields and not store them.

As you can see in issues #11 and #12, I intend to change the behaviour so only the contents of `_source` in ES would be used, and for everything else, the underlying storage would be queried.

**Comment by kbaum** [comment] 2011-06-10 21:35
Makes sense.  What would a mapping like that look like in tire.  Would it be in the mapping block?

Thanks again!

**Comment by karmi** [comment] 2011-06-10 21:43
Yes, you could configure the field `store` properties in the `mapping` block (as shown in the Readme). However, to disable source altogether (even thoug I'm not sure why to do that, for majority of cases), you would have to use something like `Tire.index('something') { create :mappings => { :mymodel => { :_source => 'disable', :properties => { ... } } } }`

**Comment by kbaum** [comment] 2011-06-11 17:13
In my case, i have a mapping for an email_message and one of the fields i am indexing is the entire message body.   

```
  mapping do

    indexes :id, :type => 'integer'
    indexes :email_account_id, :type=>'integer'
    indexes :user_id, :type=>'integer'
    indexes :from_address, :type=>'string'
    indexes :to_address, :type=>'string'
    indexes :subject, :type=>'string'
    indexes :body, :type=>'string', :analyzer => 'snowball'
    indexes :order, :type=>'boolean'
    indexes :commercial_type, :type=>'string'
    indexes :sender_type, :type=>'string'
    indexes :order_total, :type=>'double'
    indexes :unique_id, :type=>'string'
    indexes :date, :type=>'date'
    indexes :created_at, :type=>'date'
    indexes :store_domain, :type=>'string'
```

  end

I store the full message on s3 with the body so i don't want to store it again within the elastic search index as it's wasteful.  I don't care too much about the other fields as they are small but if they weren't stored in elasticsearch it would not bother me either because they can all be derived from the full message body which i have on s3 or the ids are stored within mysql.  

Is there a way to disable storage within elastic search on a per field basis or are store properties configured on the index level?  Also, i don't see store properties within the Readme.. am i missing it again?

Thanks again for all of your help!

**Comment by kbaum** [comment] 2011-06-15 02:43
Would something like this work within an initializer?

```
index_hash = EmailMessage.mapping_to_hash
index_hash[:email_message]['_source']={:enabled=>false}
EmailMessage.elasticsearch_index.create :mappings => index_hash
```

Is there any danger of corrupting an existing index with the code above?

Thanks!

**Comment by karmi** [comment] 2011-07-12 13:57
Closing, since this is a duplicate of issues #10, #11 and #12. Thanks for all the debugging!!!

**Closed as completed by karmi** 2011-07-12 13:57 UTC
