### ISSUE TITLE
Not returning expected results for a string search

### ISSUE THREAD

**Issue by charlespeach** [karmi/retire#784] opened 2013-07-05 01:52 UTC
Hiya,

Given I have a `ContentItem` class:

``` ruby
class ContentItem < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  attr_accessor :title
end
```

And I have 3 records in elastic search (and db):

```
[#<ContentItem id: 1, title: "Test 1">, 
#<ContentItem id: 2, title: "Test2">, 
#<ContentItem id: 3, title: "Test">]
```

When I call `ContentItem.search 'Test'` I get two results:

```
[#<ContentItem id: 1, title: "Test 1">, 
#<ContentItem id: 3, title: "Test">]
```

When I expect to get all 3 back. What am I missing? Does `ContentItem.search 'Test'` not return `'Test2'` because of the number?

Thanks in advanced! I am having fun using `Tire` so far :+1:

**Comment by karmi** [comment] 2013-07-05 07:08
Yes, the problem is Elasticsearch cannot see "into" words, so `Test2` is essentially the same as `TestWordLikeAGermanWouldLikeIt`. That's because it works with so called _tokens_ or _terms_ produced by the analysis process.

By default, the [standard analyzer](http://www.elasticsearch.org/guide/reference/index-modules/analysis/standard-analyzer/) is used, which uses the [standard _tokenizer_](http://www.elasticsearch.org/guide/reference/index-modules/analysis/standard-tokenizer/) to "split" your text into searchable terms.

Elasticsearch has a convenient [Analyze API](http://www.elasticsearch.org/guide/reference/api/admin-indices-analyze/), which makes it easy to test this out and get familiar with it:
- http://localhost:9200/_analyze?analyzer=standard&text=Test%202
- http://localhost:9200/_analyze?analyzer=standard&text=Test2
- etc

**Comment by karmi** [comment] 2013-07-21 14:36
Closing since not hearing back, please reopen or ping me if you any more problems.

**Closed as completed by karmi** 2013-07-21 14:36 UTC
