### ISSUE TITLE
How to filter only specific resources?

### ISSUE THREAD

**Issue by regedarek** [karmi/retire#551] opened 2012-12-19 00:03 UTC
I have two models(Answer, Question) with `app_id` attribute and I would like to show all results and only `answers` and `questions` with specific `id`.

I tried use something like below:

```
  def results
    multi_search = Tire.multi_search [:answers, :questions, :links, :service_providers]  do
      search :all do
        query { string "#{term}" }
      end
      search [:answers, :questions] do
        filter :terms, app_id:[77] 
      end
    end

    multi_search.results.first
  end
```

Is something like that possible?

I opened releated StackQuestion: http://stackoverflow.com/questions/13940005/how-to-filter-search-collection-only-if-resource-has-specific-attribute

**Comment by karmi** [comment] 2012-12-19 08:38
Yes, it is possible with the approach you outline -- use a `filtered` query for the latter. Try to stay away from the `query_string`, usually the `match` query does what you want (unless you need to support Lucene query syntax).

---

Also, please, use _either_ Github issues _or_ StackOverflow questions, it dissolves the discussion otherwise. I have noticed the question at StackOverfllow is quite different.

**Comment by karmi** [comment] 2012-12-19 08:52
Some code to get you started:

``` ruby
require 'tire'

Tire.index('questions') do
  delete
  store type: 'question', app_id: 1, title: 'Question test 1'
  store type: 'question', app_id: 2, title: 'Question test 2'
  store type: 'question', app_id: 3, title: 'Question test 3'
  refresh
end

Tire.index('links') do
  delete
  store type: 'link', app_id: 1, title: 'Link test 1'
  store type: 'link', app_id: 2, title: 'Link 2'
  store type: 'link', app_id: 3, title: 'Link test 3'
  refresh
end

Tire.index('events') do
  delete
  store type: 'event', title: 'Event test 1'
  store type: 'event', title: 'Event test 2'
  store type: 'event', title: 'Event 3'
  refresh
end

multi_search = Tire.multi_search do
  search :all, indices: [:questions, :links, :events] do
    query { match :_all, 'test' }
  end
  search :rest, indices: [:questions, :links] do
    query do
      filtered do
        query { all }
        filter :terms, app_id: [1, 2]
      end
    end
  end
end

puts "ALL:  " + multi_search.results[:all].map(&:title).inspect
puts '---'
puts "REST: " + multi_search.results[:rest].map(&:title).inspect
```

**Comment by regedarek** [comment] 2012-12-19 10:30
Thanks, now I can filter resources with `app_id`. One thing I have problem with, is how to merge results?

``` ruby
multi_search = Tire.multi_search do
  search :all, indices: [:questions, :answers, :links, :service_providers,:events, :past_events, :reviews] do
    query { match :_all, "#{term}" }
  end
  search :wihout_app, indices: [:events, :past_events, :reviews] do
    query { all }
  end
  search :with_app, indices: [:questions, :answers, :links, :service_providers] do
    query do
      filtered do
        query { all }
        filter :terms, app_id: [75]
      end
    end
  end
end
```

I would like to return `multi_search.results[:without_app] + multi_search.results[:with_app]`

 I need `content`, `type` and `highlight` attribute.

**Comment by karmi** [comment] 2012-12-19 10:33
Hmm, why query them separately and then merge them? :) In any case, just combine the array client side:

``` ruby
puts "COMBINED: " + (multi_search.results[:all].to_a | multi_search.results[:rest].to_a).map(&:title).inspect
```

**Comment by regedarek** [comment] 2012-12-19 11:08
Hmm, Maybe I oversight something:

```
puts "ALL:  " + multi_search.results[:all].map(&:title).inspect
puts '---'
puts "REST: " + multi_search.results[:rest].map(&:title).inspect
```

Gives me:

```
ALL:  ["Event test 1", "Event test 2", "Link test 1", "Link test 3", "Question test 1", "Question test 2", "Question test 3"]
---
REST: ["Link test 1", "Link 2", "Question test 1", "Question test 2"]
```

But as final result I need

```
ALL_FILTERED_BY_APP_ID:  ["Event test 1", "Event test 2", "Link test 1", "Question test 1", "Question test 2"]
```

So I guess will be better to filter that in multi search instead of merging arrays. Could you give me some hints?

**Comment by karmi** [comment] 2012-12-19 11:12
The problem is I really don't know what you're trying to do... (The code I posted just does a [union](http://www.ruby-doc.org/core-1.9.3/Array.html#method-i-7C) of those two arrays.)

**Comment by regedarek** [comment] 2012-12-19 11:39
Basically because two of my models has not `app_id` attribute i want to filter rest of them(with `app_id`) in search and keep the highest performance if it is possible.

Using union does not work for me, I receive:

``` ruby
ALL:  ["Link test 3", "Question test 1", "Question test 3", "Event test 1", "Event test 2", "Link test 1", "Question test 2"]
---
REST: ["Link 2", "Link test 1", "Question test 2", "Question test 1"]
---
COMBINED: ["Link test 3", "Question test 1", "Question test 3", "Event test 1", "Event test 2", "Link test 1", "Question test 2", "Link 2", "Link test 1", "Question test 2", "Question test 1"]
```

So I get unecessry `Link 2` and duplication of `Question test 1, Question test 2` and `Link test 1, Link test 2`

Sorry for bothering you because I guess there should be a simple solution.

EDIT:
For now something like below works for me:

``` ruby
multi_search = Tire.multi_search do
  search :without_app, indices: [:events, :past_events, :reviews] do
    query { match :_all, "#{term}" }
  end
  search :with_app, indices: [:questions, :answers, :links, :service_providers] do
    query do
      filtered do
        query { match :_all, "#{term}" }
        filter :terms, app_id: app_ids
      end
    end
  end
end
multi_search.results[:with_app].to_a + multi_search.results[:without_app].to_a
```

**Comment by karmi** [comment] 2013-01-04 15:52
Closing as answered here and on [StackOverflow](http://stackoverflow.com/questions/13940005/how-to-filter-search-collection-only-if-resource-has-specific-attribute).

**Closed as completed by karmi** 2013-01-04 15:52 UTC
