### ISSUE TITLE
Best way to show only published documents

### ISSUE THREAD

**Issue by niuage** [karmi/retire#276] opened 2012-03-12 02:45 UTC
Hey,

Seems like a simple requirement, but I'm not sure how to handle it.
My documents have a `published_at` field. I don't want to get unpublished documents in the search results.
Until now I've been using a `range`, with `range :published_at, gt: 1.year.ago`, something like that.

Is there a nicer way? Something like `must_not { term :published_at, nil  }` ?

Thanks

**Comment by karmi** [comment] 2012-03-12 08:09
Hi, a best to use a filter here, since it's nicely cacheable -- if the documents downright _miss_ field, the [_exists_](http://www.elasticsearch.org/guide/reference/query-dsl/exists-filter.html) filter could be put to great use here:

``` ruby
require 'tire'

Tire.index 'test-published_filter' do
  delete
  create

  store title: 'Document 1 (published)', published_at: Time.now
  store title: 'Document 2 (unpublished)'
  refresh
end

s = Tire.search 'test-published_filter' do
  query { string 'document' }
  filter :exists, field: 'published_at'

  STDERR.puts to_curl
end

puts "---", s.results.to_a.inspect
```

**Comment by niuage** [comment] 2012-03-12 12:25
Thanks.
But filters dont affect facet counts, right? Unpublished documents would then make my facet counts appear wrong.
I'm using mysql to store my documents, so the field exists, it's just nil.

**Comment by karmi** [comment] 2012-03-12 13:06
>  filters dont affect facet counts (...)

Right! In that case, you can use the boolean query and the `_exists_` query. It could make more sense to have some specific property `published=true|false` for better legibility, though...

``` ruby
require 'tire'

Tire.index 'test-published_filter' do
  delete
  create

  store title: 'Document 1 (published)',   published_at: Time.now
  store title: 'Document 2 (unpublished)', published_at: nil
  refresh
end

s = Tire.search 'test-published_filter' do
  query do
    boolean do
      must { string 'document' }
      must { string "_exists_:document.published_at" }
    end
  end

  STDERR.puts to_curl
end

puts "---", s.results.to_a.inspect

```

**Comment by niuage** [comment] 2012-03-12 13:29
Ok, thanks a lot ;)

**Comment by karmi** [comment] 2012-03-12 13:32
You're welcome, please just close the issue if/when the problem is solved...

**Closed as completed** 2012-03-12 13:37 UTC
