### ISSUE TITLE
raise timeouts

### ISSUE THREAD

**Issue by rb2k** [karmi/retire#113] opened 2011-09-28 21:06 UTC
It would be nice if the default timeouts were a bit longer. Especially with complicated queries that take a while, Tire seems to time out after a relatively short time and return "false" as a result. I think it wouldn't hurt anybody if the timeouts were either customizable or raised to e.g. 90 seconds by default :)

Cheers,
Marc

**Comment by karmi** [comment] 2011-09-29 04:48
Yes, the immediately looming wave of bugfixes, refactorings and additions will have to include this -- configurable timeouts.

**Comment by karmi** [comment] 2011-09-29 13:05
Duplicate of karmi/tire#89.

**Closed as completed by karmi** 2011-09-29 13:05 UTC

**Comment by rb2k** [comment] 2011-11-07 11:36
That wasn't actually a duplicate :)  
karmi/tire#89 is about supporting the timeout flag elasticsearch provides
This was more about the HTTP drivers not closing down before ES finishes

**Comment by karmi** [comment] 2011-11-07 21:05
You mean this is about timeouts for the HTTP client Tire uses (RestClient, Curb)? The defaults should be something like 60sec which should be enough for most queries? (I've never seen a client timing out myself.)

**Comment by rb2k** [comment] 2011-11-07 21:08
I always had the impression that RestClient has a shorter timeout while Curb has a longer one. I run ES on a single server with a lot of data, so my queries can take a minute or two at times :-/

**Comment by karmi** [comment] 2011-11-07 21:12
Not sure how well RestClient supports timeouts: https://github.com/archiloque/rest-client/blob/master/lib/restclient/request.rb#L23

**Comment by karmi** [comment] 2011-11-08 06:32
@rb2k: Actually, you can try it out pretty easily.

Just monkeypatch the following lines from [client.rb](https://github.com/karmi/tire/blob/master/lib/tire/http/client.rb#L9-13):

``` ruby
def self.get(url, data=nil)
  perform ::RestClient::Request.new(:method => :get, :url => url, :payload => data).execute
rescue ::RestClient::Exception => e
  Response.new e.http_body, e.http_code
end
```

Put some timeout into the `::RestClient::Request` constructor and see what happens. I'm not terribly against increasing the timeout here to 5 or 10 minutes -- everybody can/should just wrap it in their own timeout logic, then.
