### ISSUE TITLE
Search using DSL directly

### ISSUE THREAD

**Issue by ghost** [karmi/retire#356] opened 2012-05-30 13:50 UTC
In version 0.3.12 I could do:

``` Ruby
search = Tire.search 'users', 
        query: {
          constantScore: { 
            filter: { 
              terms: { linkedin_id: linkedin_connections }
            }
          }
        }
```

In the latest version, I can no longer do this. It seems that it's putting the entire data section into the payload, which is put into the URL, and thus becomes too long since the `linkedin_connections` may have 1,000 elements.

Is there a better way to do this so it just makes the post request with the data section now?

**Comment by ghost** [comment] 2012-05-30 14:04
On further investigation, it seems that the older version (0.3.12) would do a `POST` request, where as, the latest, is trying to do a `GET` and putting the data elements into the query string, which ends up in a 413 HTTP error because there's too much. Is there a way to force it to do a `POST` request?

**Comment by vhyza** [comment] 2012-06-20 12:33
Hello,

you can try `curb` client using

``` ruby
require 'tire'
require 'tire/http/clients/curb'

Tire.configure { client Tire::HTTP::Client::Curb }
```

in fact this client is using `POST` request instead `GET` (https://github.com/karmi/tire/blob/master/lib/tire/http/clients/curb.rb#L18-20)

**Comment by brandonhilkert** [comment] 2012-06-20 12:35
Cool thanks.

**Comment by karmi** [comment] 2012-10-19 11:38
Closing the issue, since the problem is solved.

**Closed as completed by karmi** 2012-10-19 11:38 UTC
