### ISSUE TITLE
Tire::Model::Callbacks prevents object deletion

### ISSUE THREAD

**Issue by roccoblues** [karmi/retire#70] opened 2011-08-12 11:13 UTC
When I include Tire::Model::Callbacks in a model the records are no longer removed on destroy() from the database. All associations are deleted and also the Elastic Search Index gets update but the final delete statement is never run.

So far I had no luck narrowing it down. Any ideas where to look?

This is with Rails 3.0.9 and tire 0.1.16.

**Comment by karmi** [comment] 2011-08-15 15:31
Hi,

this is _very_ unexpected behaviour. I've double-checked in an app, and also tightened up the integration tests for this. Could you provide more info about what ORM is this concerning, and possibly some snippets to recreate, please?

**Comment by roccoblues** [comment] 2011-08-16 13:20
It also fails with a clean model in the same app. Here's my model:

```
class TireTest < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks
end
```

testcase in the console:

```
:001 > t = TireTest.new
 => #<TireTest id: nil, name: nil, created_at: nil, updated_at: nil> 
:002 > t.name = 'test'
 => "test" 
:003 > t.save
 => true 
:004 > t.destroy
 => #<TireTest id: 2, name: "test", created_at: "2011-08-16 13:12:34", updated_at: "2011-08-16 13:12:34"> 
:005 > t = Tiretest.find(2)
 => #<TireTest id: 2, name: "test", created_at: "2011-08-16 13:12:34", updated_at: "2011-08-16 13:12:34">
```

the log:

```
SQL (0.1ms)  BEGIN
SQL (1.0ms)  SHOW TABLES
SQL (1.8ms)  describe `tire_tests`
AREL (0.3ms)  INSERT INTO `tire_tests` (`name`, `created_at`, `updated_at`) VALUES ('test', '2011-08-16 13:12:34', '2011-08-16 13:12:34')
SQL (2.2ms)  COMMIT
SQL (0.1ms)  BEGIN
SQL (0.2ms)  COMMIT
TireTest Load (0.3ms)  SELECT SQL_NO_CACHE `tire_tests`.* FROM `tire_tests` WHERE `tire_tests`.`id` = 2 LIMIT 1
```

same test without `include Tire::Model::Callbacks`

```
SQL (0.1ms)  BEGIN
SQL (0.8ms)  SHOW TABLES
SQL (1.9ms)  describe `tire_tests`
AREL (0.3ms)  INSERT INTO `tire_tests` (`name`, `created_at`, `updated_at`) VALUES ('test', '2011-08-16 13:18:37', '2011-08-16 13:18:37')
SQL (0.7ms)  COMMIT
SQL (0.1ms)  BEGIN
AREL (0.3ms)  DELETE FROM `tire_tests` WHERE `tire_tests`.`id` = 4
SQL (1.5ms)  COMMIT
```

I'll try to remove some gems and see if that fixes it.

**Comment by karmi** [comment] 2011-08-16 13:38
Hi, I've tried out your scenario in a fresh app (Ruby 1.8.7, Rails 3.0.8):

   rails g scaffold tire_test name:string

Added the _Tire_ includes. Now, both `TireTest#destroy` and `TireTest#delete` do delete the record from the db, in a console session replicated after yours.

Obviously, the `TireTest#delete` does not delete the record from ElasticSearch, because it does not run any hooks.

I'm wondering what might be causing this issue for you. Could you try in a fresh app the way I did?

**Comment by roccoblues** [comment] 2011-08-16 13:48
I have the feeling that I'll end up with a nice _facepalm_. :) Anyway here's a test app where I can reproduce the behavior: https://github.com/roccoblues/TireTest

**Comment by karmi** [comment] 2011-08-16 16:58
Thanks, cloned, wasted half an hour to install mysql :), and everything works. Both `delete` and `destroy` correctly issue `DELETE FROM ...` statements in the console... This is the sequence of my commands:

```
~/Playground/ElasticSearch/Tire/TireTest
karmi▹ rake db:create
karmi▹ rake db:migrate
==  CreateTestModels: migrating ===============================================
-- create_table(:test_models)
   -> 0.0241s
==  CreateTestModels: migrated (0.0247s) ======================================

karmi▹ rails console
Loading development environment (Rails 3.0.9)
>> ActiveRecord::Base.logger = Logger.new(STDOUT)
>> ActiveRecord::Base.clear_active_connections!

>> t = TestModel.new :name => 'TEST'
=> #<TestModel id: nil, name: "TEST", created_at: nil, updated_at: nil>
>> t.save
  SQL (0.2ms)  BEGIN
  SQL (0.6ms)  SHOW TABLES
  SQL (1.9ms)  describe `test_models`
  AREL (0.4ms)  INSERT INTO `test_models` (`created_at`, `name`, `updated_at`) VALUES ('2011-08-16 16:54:30', 'TEST', '2011-08-16 16:54:30')
  SQL (0.6ms)  COMMIT
=> true

>> t.delete
  AREL (0.9ms)  DELETE FROM `test_models` WHERE `test_models`.`id` = 1
=> #<TestModel id: 1, name: "TEST", created_at: "2011-08-16 16:54:30", updated_at: "2011-08-16 16:54:30">

>> TestModel.elasticsearch_index.delete
=> true
>> t = TestModel.new :name => 'TEST'
=> #<TestModel id: nil, name: "TEST", created_at: nil, updated_at: nil>
>> t.save
  SQL (0.1ms)  BEGIN
  AREL (0.5ms)  INSERT INTO `test_models` (`created_at`, `name`, `updated_at`) VALUES ('2011-08-16 16:55:45', 'TEST', '2011-08-16 16:55:45')
  SQL (0.5ms)  COMMIT
=> true
>> t.destroy
  SQL (0.1ms)  BEGIN
  AREL (1.0ms)  DELETE FROM `test_models` WHERE `test_models`.`id` = 2
  SQL (0.5ms)  COMMIT
=> #<TestModel id: 2, name: "TEST", created_at: "2011-08-16 16:55:45", updated_at: "2011-08-16 16:55:45">
>> quit
```

**Comment by roccoblues** [comment] 2011-08-17 08:40
that's getting really strange. I'll try to poke into it with the debugger today. Thanks for you help so far!

**Comment by roccoblues** [comment] 2011-08-17 08:43
one more question: do you have an elasticsearch server running during your tests?

**Comment by roccoblues** [comment] 2011-08-17 08:52
I'm really not making this up. ;)

```
 > t = TestModel.new :name => 'TEST'
 => #<TestModel id: nil, name: "TEST", created_at: nil, updated_at: nil> 
 > t.save
  SQL (0.2ms)  BEGIN
  SQL (0.4ms)  SHOW TABLES
  SQL (2.1ms)  describe `test_models`
  AREL (0.3ms)  INSERT INTO `test_models` (`name`, `created_at`, `updated_at`) VALUES ('TEST', '2011-08-17 08:49:41', '2011-08-17 08:49:41')
  SQL (0.7ms)  COMMIT
 => true 
 > t.delete
  AREL (0.8ms)  DELETE FROM `test_models` WHERE `test_models`.`id` = 10
 => #<TestModel id: 10, name: "TEST", created_at: "2011-08-17 08:49:41", updated_at: "2011-08-17 08:49:41"> 
 > TestModel.elasticsearch_index.delete
 => true 
 > t = TestModel.new :name => 'TEST'
 => #<TestModel id: nil, name: "TEST", created_at: nil, updated_at: nil> 
 > t.save
  SQL (0.1ms)  BEGIN
  AREL (0.2ms)  INSERT INTO `test_models` (`name`, `created_at`, `updated_at`) VALUES ('TEST', '2011-08-17 08:50:09', '2011-08-17 08:50:09')
  SQL (4.9ms)  COMMIT
 => true 
 > t.destroy
  SQL (0.1ms)  BEGIN
  SQL (0.2ms)  COMMIT
 => #<TestModel id: 11, name: "TEST", created_at: "2011-08-17 08:50:09", updated_at: "2011-08-17 08:50:09"> 
 > quit
```

**Comment by roccoblues** [comment] 2011-08-17 09:27
If I comment out this code in `Tire::Model::Callbacks`

```
    if base.respond_to?(:before_destroy) && !base.instance_methods.include?('destroyed?')
      base.class_eval do
        before_destroy  { @destroyed = true }
        def destroyed?; !!@destroyed; end
      end
    end
```

it works. Somehow that seems to conflict with ActiveRecord. I'll dig deeper.

**Comment by roccoblues** [comment] 2011-08-17 09:35
oh boy I am already deeper into rails code than I ever wanted. Shouldn't this return true for ActiveRecord models?

```
  > TestModel.instance_methods.include?('destroyed?')
    => false
```

**Closed as completed** 2011-08-18 06:14 UTC

**Comment by karmi** [comment] 2011-08-18 06:17
Yeah, crap, the reason we've seen different behaviours was I was on 1.8.x and you, probably, on 1.9.x. Compare:

```
$ irb
>> puts RUBY_VERSION
1.8.7
=> nil
>> Object.instance_methods
=> ["inspect", "tap" ...

$ irb
>> puts RUBY_VERSION
1.9.2
=> nil
>> Object.instance_methods
=> [:nil?, :=== ...
```

`instance_method` on Ruby 1.9 returns symbols -- I've been hit with it before. Thanks for the report and pull request, it should be fixed now!
