### ISSUE TITLE
Receiving a MultiJson::DecodeError (A JSON text must at least contain two octets!) Error

### ISSUE THREAD

**Issue by cameronkendall** [karmi/retire#505] opened 2012-11-09 01:49 UTC
I just upgraded to 0.5.0 (from 0.4.3) and I immediately get this error when I load any page.  The only solution is for me to remove the mappings block:

  mapping do
    indexes :title
    indexes :content
  end

This is how my model looks like:
class Article
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Tire::Model::Search
  include Tire::Model::Callbacks

  field :title, type: String
  field :content, type: String

  index_name "articles-index"

  # If i remove starting here
  mapping do
    indexes :title
    indexes :content
  end
  # ending here it works fine

  # ... other methods
end

After removing the block it runs fine but I'm assuming this is not the the correct way to go about this..  Thanks.

**Comment by karmi** [comment] 2012-11-09 07:48
Weird -- please try to run the https://github.com/karmi/tire/blob/master/test/integration/mongoid_searchable_test.rb test and report back the status. Should run fine.

**Comment by karmi** [comment] 2012-11-09 07:49
Also, please give a relevant part of the error backtrace, ie. the error being traced to some line in Tire codebase -- the error by itself does not say much.

**Comment by cameronkendall** [comment] 2012-11-09 19:28
Whats the command to run that test?  I've never run a test from a ruby gem before.  I've only run tests that I created locally for my project.

**Comment by karmi** [comment] 2012-11-09 19:42
1. Git clone the project and `cd` into it
2. Run `bundle install`
3. Run `bundle exec ruby -I lib:test test/integration/mongoid_searchable_test.rb`

(Run `bundle exec rake test` to run all the tests.)

**Comment by darrenboyd** [comment] 2012-11-09 21:48
I'm seeing a similar error. I'm in a Rails application, with ActiveRecord Persistence.

```
A JSON text must at least contain two octets!
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/json-1.7.5/lib/json/common.rb:155:in `initialize'
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/json-1.7.5/lib/json/common.rb:155:in `new'
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/json-1.7.5/lib/json/common.rb:155:in `parse'
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/multi_json-1.3.7/lib/multi_json/adapters/json_common.rb:7:in `load'
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/multi_json-1.3.7/lib/multi_json.rb:96:in `load'
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/tire-0.5.0/lib/tire/index.rb:324:in `logged'
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/tire-0.5.0/lib/tire/index.rb:21:in `exists?'
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/tire-0.5.0/lib/tire/model/indexing.rb:107:in `create_elasticsearch_index'
/Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/tire-0.5.0/lib/tire/model/indexing.rb:61:in `mapping'
/Users/dboyd/Code/client_portal/app/models/content.rb:16:in `<class:Content>'
/Users/dboyd/Code/client_portal/app/models/content.rb:5:in `<top (required)>'
```

Line 5 of content.rb is...

`class Content < ActiveRecord::Base`

Line 16 is...

`tire.mapping do`

This is happening from `Tire::Index#exists?`, which gets logged.

in `Tire::Index#logged` we see (starting at line 323)...

``` ruby
body = if @response
  MultiJson.encode( MultiJson.load(@response.body), :pretty => Configuration.pretty)
else
  MultiJson.encode( MultiJson.load(error.message), :pretty => Configuration.pretty) rescue ''
end
```

Of course, the request was `curl -I "http://localhost:9200/contents"`, and it was successful.  Which means the body is going to be empty, which is invalid as JSON.

**Comment by cameronkendall** [comment] 2012-11-09 22:20
I passed all of the mongoid_searchable_test.rb tests but when I ran all of the tests I received:

```
734 tests, 722 passed, 8 failures, 4 errors, 0 skips, 1574 assertions
```

Here are the failures and errors I did a cut and paste of:

[cut]

**Comment by karmi** [comment] 2012-11-10 08:59
@darrenboyd All right, so it happens when you have `Tire.configure { logger STDERR, level: 'debug' }` set, right?

**Comment by darrenboyd** [comment] 2012-11-12 16:17
Yes.  When I change it to `level: 'info'`, the problem goes away (at least, it doesn't present itself when running `$ rake environment`).

**Comment by Odaeus** [comment] 2012-11-13 12:50
I can confirm this issue. Well done for working out it's the log level setting!

**Comment by darrenboyd** [comment] 2012-11-13 16:44
I've been trying to debug this by adding a test to index_test that fails.  I am running into some very odd behavior in the tests.  For example, the following test passes...

``` ruby
  should "fail on blank json" do
    MultiJson.load('')
  end
```

And yet, if I load the gem into an IRB environment, I see different behavior...

``` ruby
newton ~/src/tire master$ bundle exec irb -Ilib
irb> require 'tire'
  => true
irb> MultiJson.load('')
MultiJson::DecodeError: no object read at line 1, column 1 [load.c:1038]
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/multi_json-1.3.7/lib/multi_json/adapters/oj.rb:17:in `load'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/multi_json-1.3.7/lib/multi_json/adapters/oj.rb:17:in `load'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p286/gems/multi_json-1.3.7/lib/multi_json.rb:96:in `load'
    from (irb):2
    from /Users/dboyd/.rvm/rubies/ruby-1.9.3-p286/bin/irb:16:in `<main>'
```

This latter behavior makes sense.  An empty String is not a valid JSON object (AFAIK).

Thoughts?

**Comment by Odaeus** [comment] 2012-11-13 17:12
@darrenboyd I think this depends on the backend you are using. The one you are using there is "OJ", which is a development dependency of Tire. I think that because you are executing it within the Tire source directory with bundler it is picking up OJ and using that as the backend.

MultiJson should probably be normalising this behaviour, rather than some backends producing exceptions and others simply nil.

**Comment by darrenboyd** [comment] 2012-11-13 20:57
@Odaeus I believe the JSON libraries are behaving properly.  From what I understand, the empty string is not valid JSON.  At least, it doesn't appear that it is from the grammar found here: http://www.json.org/

I believe this issue is with the caller  (the 'logged' method in Index).

**Comment by johnnyrodgers** [comment] 2012-12-02 01:17
I can confirm this issue. I've set the following in an initializer:

```
Tire.configure do
    logger 'elasticsearch.log', :level => 'debug'
end
```

But when I start the Rails server (thin, in my case), I get this error:

```
/Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/json-1.7.5/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (MultiJson::DecodeError)
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/json-1.7.5/lib/json/common.rb:155:in `new'
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/json-1.7.5/lib/json/common.rb:155:in `parse'
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/multi_json-1.3.6/lib/multi_json/adapters/json_common.rb:7:in `load'
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/multi_json-1.3.6/lib/multi_json.rb:93:in `load'
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/tire-0.5.1/lib/tire/index.rb:377:in `logged'
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/tire-0.5.1/lib/tire/index.rb:21:in `exists?'
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/tire-0.5.1/lib/tire/model/indexing.rb:107:in `create_elasticsearch_index'
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/tire-0.5.1/lib/tire/model/indexing.rb:61:in `mapping'
    from /Users/johnnyrodgers/.rvm/gems/ruby-1.9.2-p290/gems/tire-0.5.1/lib/tire/model/search.rb:296:in `mapping'
```

Changing the log level to 'info' fixes the error.

**Comment by darrenboyd** [comment] 2012-12-03 16:49
I didn't realize that issue 'mentions' get propagated across forks... 

The small change referenced above (here: https://github.com/darrenboyd/tire/commit/4ee579b79), _should_ address this problem.  However, I'm reluctant to request a pull request for a couple reasons.

I am unable to get the tests passing in my local environment.  This includes the index_test that is directly related (I have 1 failure).

There seems to be some dark magic going on in the test environment.  MultiJson.load behaves differently in the tire test environment than it does in irb.  For example...

```
~/src/tire $ bundle exec irb
irb> require 'multi_json'
  => true
irb> MultiJson.load('')
MultiJson::DecodeError: no object read at line 1, column 1 [load.c:1038]
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/multi_json-1.3.7/lib/multi_json/adapters/oj.rb:17:in `load'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/multi_json-1.3.7/lib/multi_json/adapters/oj.rb:17:in `load'
    from /Users/dboyd/.rvm/gems/ruby-1.9.3-p327/gems/multi_json-1.3.7/lib/multi_json.rb:96:in `load'
    from (irb):2
    from /Users/dboyd/.rvm/rubies/ruby-1.9.3-p327/bin/irb:16:in `<main>'
```

However, this test passes...

``` ruby
  should "fail on blank json" do
    MultiJson.load('')
  end
```

Which effectively means testing my change to `#logged` is not possible, since the failure scenario will not fail in the test environment.

**Comment by karmi** [comment] 2012-12-03 17:40
Hi all, thanks for the debugging! It's indeed a case of empty string, see following isolated test case:

``` ruby
require 'json'
require 'oj'
require 'yajl'

begin
  puts "Yajl:" + Yajl::Parser.parse('').inspect
rescue Exception => e
  puts "Yajl exception:", e.inspect
end

begin
  puts "Oj:" + Oj.load('').inspect
rescue Exception => e
  puts "Oj exception:", e.inspect
end

begin
  puts "JSON" + JSON.parse('').inspect
rescue Exception => e
  puts "JSON exception:", e.inspect
end
```

Should be fixed in the closing commit, could you test it?

**Comment by karmi** [comment] 2012-12-03 17:42
@darrenboyd Thanks!, solved it a bit differently, but the principle stands -- check for actually having something in the response body.

**Closed as completed** 2012-12-03 17:41 UTC
