### ISSUE TITLE
How to pass searched values in instance variable?

### ISSUE THREAD

**Issue by shubhanshu-gupta** [karmi/retire#757] opened 2013-06-18 09:57 UTC
I am implementing Elastic search for searching users and their friends in my project. I am able to successfully search users but not the friends. Below I am pasting relevant portion of my User model, user friendship model, user friendship controller.

user.rb

``` ruby
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  include Tire::Model::Search
  include Tire::Model::Callbacks



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable,:confirmable,:token_authenticatable,:authentication_keys=>[:login]


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :full_name, :user_name,:birthday,:gender,
                  :country,:state,:profile_picture, :user_friendships
```

user_friendship.rb

``` ruby
class UserFriendship < ActiveRecord::Base

  include Tire::Model::Search
  include Tire::Model::Callbacks


  attr_accessible :user, :friend, :user_id, :friend_id, :state

  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  validate :friend_not_self

  def friend_not_self
    errors.add(:base, "User and friends can not be same") if user.id == friend.id
  end
```

user_friendship_controller.rb

``` ruby
class UserFriendshipsController < ApplicationController

before_filter :authenticate_user!
respond_to :html, :json

def index


if params[:query].present?
     @user_friendships = current_user.user_friendships.search(params[:query], load: true)
 else
     @user_friendships = current_user.user_friendships.all
 end 


case params[:list]
when nil
  @user_friendships = current_user.pending_user_friendships.all + current_user.accepted_user_friendships.all + current_user.requested_user_friendships.all
when 'Blocked'
  @user_friendships = current_user.blocked_user_friendships.all
when 'Pending'
  @user_friendships = current_user.pending_user_friendships.all
when 'Accepted'
  @user_friendships = current_user.accepted_user_friendships.all
when 'Requested'
  @user_friendships = current_user.requested_user_friendships.all
end
respond_with @user_friendships
end
```

What I think is, possibly in my user friendship controller I am passing a variable in an instance variable whereas while searching for users the code i wrote looks like:

``` ruby
def index
if params[:query].present?
     @users = User.search(params[:query], load: true)
 else
     @users = User.all
 end 
```

wherein I am passing the class User. When I did the same thing in case of user friendship, that is @user_friendships = UserFriendship.search(params[:query], load: true), there was no result. So, what should be the possible solution so that the search result for user friendship are also displayed that is what should i pass as a search query in my user frienship controller. Moreover, in user search also, only the new users who have just signed up are displayed. Not the old ones. Is there a problem in mapping or indexing from my side? Please correct me where I am going wrong.

**Comment by karmi** [comment] 2013-06-18 11:26
Please see http://stackoverflow.com/questions/11692560/elasticsearch-tire-and-nested-queries-associations-with-activerecord/11711477#11711477.

Closing as duplicate of http://stackoverflow.com/questions/17151596/how-to-use-elasticsearch-using-tire-gem.

**Closed as completed by karmi** 2013-06-18 11:26 UTC
