### ISSUE TITLE
Time as query value causing ElasticSearch error

### ISSUE THREAD

**Issue by weynsee** [karmi/retire#510] opened 2012-11-11 05:46 UTC
When I specify a Time value in a Tire query it causes an ElasticSearch exception. Here is a sample issue demonstrating the issue:

```
Tire.index 'articles' do
  delete

  create :mappings => {
    :article => {
      :properties => {
        :published_on => { :type => 'date', :index => 'not_analyzed' }
      }
    }
  }

  store :type => 'article', :published_on => Time.now
  refresh
end

s = Tire.search('articles') do
  filter :range, :published_on => { :gte => Time.now }
end
```

It seems the value sent to ElasticSearch in the query is in an unexpected format. The relevant part of the exception is

Parse Failure [Failed to parse source [{\n  \"filter\":{\n    \"range\":{\n      \"published_on\":{\n        \"gte\":1352612111.780873000\n      }\n    }\n  }}]]]; nested: ElasticSearchParseException[failed to parse date field [1352612111.780873000], tried both date format [dateOptionalTime], and timestamp number]; nested: IllegalArgumentException[Invalid format: \"1352612111.780873000\" is malformed at \"1.780873000\"]; }

I've verified that this code works on 0.4.3 and not on 0.5.0.

**Comment by karmi** [comment] 2012-11-11 10:02
Hey, this is strange -- the problem is of course the time is incorrectly serialized into JSON, however, the behaviour is the same for me on master (0.5.0) and 0.4.3:

```
git checkout master # karmi/tire@463ad4d
ruby -rubygems -I lib -r tire -e 'puts Tire::VERSION; puts Tire.search("articles") {filter :range, published_on: { gte: Time.now }}.to_curl'
0.5.0
curl -X GET 'http://localhost:9200/articles/_search?pretty' -d '{
  "filter":{
    "range":{
      "published_on":{
        "gte":1352627975.257754000
      }
    }
  }}'


git checkout v0.4.3
ruby -rubygems -I lib -r tire -e 'puts Tire.search("articles") {filter :range, published_on: { gte: Time.now }}.to_curl'
curl -X GET "http://localhost:9200/articles/_search?pretty=true" -d '{"filter":{"range":{"published_on":{"gte":1352628020.300750000}}}}'
```

**Comment by weynsee** [comment] 2012-11-11 13:55
It seems MultiJson loaded Oj when I ran the query, I just tried it with Yajl and got a different format for the value. For now I've worked around it by specifying a format recognized by ElasticSearch (i.e. strftime to ISO 8601). Do you think it'll be useful to do the formatting in Tire itself?

**Comment by karmi** [comment] 2012-11-11 13:59
True, `YAJL` encodes the date correctly, `oj` as a floating point number:

```
ruby -rubygems -I lib -r tire -r yajl/json_gem -e 'puts Tire.search("articles") {filter :range, published_on: { gte: Time.now }}.to_curl'
curl -X GET 'http://localhost:9200/articles/_search?pretty' -d '{
  "filter": {
    "range": {
      "published_on": {
        "gte": "2012-11-11 14:57:48 +0100"
      }
    }
  }
}'
```

I'd be _very_ cautious about pre-processing values before they are JSON-ified (potential performance issues, etc), but clearly, we have to deal with a situation like this. From the usability standpoint, you certainly want to write your query just as you did, no matter what JSON library you use...

**Comment by weynsee** [comment] 2012-11-12 03:46
Yeah pre-processing values doesn't seem like an elegant solution for this. Another option I'm thinking of is if we can somehow specify the time format for the JSON library when serializing. I know `oj` supports it through the `time_format` option:

```
MultiJson.encode(Time.now, time_format: :xmlschema)
```

but I doubt that this will work for all JSON libraries supported by MultiJson.

**Comment by karmi** [comment] 2012-12-11 20:40
@weynsee Sorry for the delay. I think JSON libraries usually just ignore the `options` sent to them, so if this fixes the issue with `oj`, we should go for it... Can you quickly check how it behaves when you use eg. `yajl` or the default `json` in your code?

**Comment by weynsee** [comment] 2012-12-12 02:46
Yep, the extra options are ignored by the other json libraries. I just checked the other json libraries and their default format for Time is supported by ElasticSearch, so only `oj` has this problem.

```
1.9.3p327 :001 > require 'multi_json'
 => true
1.9.3p327 :002 > MultiJson.use :oj
 => MultiJson::Adapters::Oj
1.9.3p327 :003 > MultiJson.encode Time.now
 => "1355280070.200394000"
1.9.3p327 :004 > MultiJson.encode Time.now, time_format: :xmlschema
 => "\"2012-12-12T10:41:14.717244000+08:00\""
1.9.3p327 :005 > MultiJson.use :yajl
 => MultiJson::Adapters::Yajl
1.9.3p327 :006 > MultiJson.encode Time.now, time_format: :xmlschema
 => "\"2012-12-12 10:41:28 +0800\""
1.9.3p327 :007 > MultiJson.use :json_gem
 => MultiJson::Adapters::JsonGem
1.9.3p327 :008 > MultiJson.encode Time.now, time_format: :xmlschema
 => "\"2012-12-12 10:41:48 +0800\""
1.9.3p327 :009 > MultiJson.use :json_pure
 => MultiJson::Adapters::JsonPure
1.9.3p327 :010 > MultiJson.encode Time.now, time_format: :xmlschema
 => "\"2012-12-12 10:41:59 +0800\""
1.9.3p327 :011 > MultiJson.use :ok_json
 => MultiJson::Adapters::OkJson
1.9.3p327 :012 > MultiJson.encode Time.now, time_format: :xmlschema
 => "\"2012-12-12 10:42:15 +0800\""
```

**Comment by karmi** [comment] 2012-12-17 09:07
@weynsee Thanks for the debugging! I'll look into the places we need to add the `:xmlschema` serialization.

**Comment by jeremygpeterson** [comment] 2012-12-28 21:19
I'll dive into this one.

**Comment by jeremygpeterson** [comment] 2012-12-29 21:23
I reviewed MultiJson and they've resolved this issue December 11th.  It's not released yet, but we'll have very little to change in Tire.

**Comment by karmi** [comment] 2013-02-07 06:23
@jeremygpeterson @weynsee Is the issue gone with the latest multi_json release?

**Comment by weynsee** [comment] 2013-02-07 08:04
It's still happening with oj (2.0.3) with multi_json (1.5.0)

**Comment by karmi** [comment] 2013-03-07 16:14
Seems to be fixed now:

```
>>  require 'multi_json'
>> MultiJson.use :oj

>> MultiJson.encode Time.now
=> "\"2013-03-07 17:13:01 +0100\""
```

Notice `oj` doesn't handle `Time` well by default:

```
>> Oj.dump(Time.now)
=> "{\"^t\":1362672809.122553000}"

>> Oj.dump(Time.now.iso8601)
=> "\"2013-03-07T17:13:44+01:00\""
```

**Closed as completed by karmi** 2013-03-07 16:14 UTC
Labels: enhancement, reminder
